# Generated by Django 6.0.1 on 2026-01-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=80)),
                ('cliente_telefono', models.CharField(max_length=40)),
                ('fecha_visita', models.DateField()),
                ('fecha_reserva', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('ruedo_saco', models.CharField(blank=True, default='', max_length=40)),
                ('ruedo_pantalon', models.CharField(blank=True, default='', max_length=40)),
                ('notas', models.TextField(blank=True, default='')),
                ('senia_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('senia_metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('MercadoPago', 'MercadoPago'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_restante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('MercadoPago', 'MercadoPago'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=20)),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Entregado', 'Entregado'), ('Disponible', 'Disponible')], default='Reservado', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prendas', models.ManyToManyField(related_name='alquileres', to='prendas.prenda')),
            ],
        ),
    ]
