# Generated by Django 6.0.1 on 2026-01-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Saco', 'Saco'), ('Pantalón', 'Pantalón'), ('Camisa', 'Camisa'), ('Chaleco', 'Chaleco'), ('Moño', 'Moño'), ('Corbata', 'Corbata'), ('Zapatos', 'Zapatos')], max_length=20)),
                ('color', models.CharField(max_length=40)),
                ('marca', models.CharField(blank=True, default='', max_length=40)),
                ('talle', models.CharField(max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Entregado', 'Entregado')], default='Disponible', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
